/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.navercorp.pinpoint.thrift.dto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-2-9")
public class TDevices implements org.apache.thrift.TBase<TDevices, TDevices._Fields>, java.io.Serializable, Cloneable, Comparable<TDevices> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDevices");

  private static final org.apache.thrift.protocol.TField T_DEVICES_FIELD_DESC = new org.apache.thrift.protocol.TField("tDevices", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TDevicesStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TDevicesTupleSchemeFactory());
  }

  private List<TDeviceInfo> tDevices; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    T_DEVICES((short)1, "tDevices");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // T_DEVICES
          return T_DEVICES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.T_DEVICES, new org.apache.thrift.meta_data.FieldMetaData("tDevices", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TDeviceInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDevices.class, metaDataMap);
  }

  public TDevices() {
  }

  public TDevices(
    List<TDeviceInfo> tDevices)
  {
    this();
    this.tDevices = tDevices;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDevices(TDevices other) {
    if (other.isSetTDevices()) {
      List<TDeviceInfo> __this__tDevices = new ArrayList<TDeviceInfo>(other.tDevices.size());
      for (TDeviceInfo other_element : other.tDevices) {
        __this__tDevices.add(new TDeviceInfo(other_element));
      }
      this.tDevices = __this__tDevices;
    }
  }

  public TDevices deepCopy() {
    return new TDevices(this);
  }

  @Override
  public void clear() {
    this.tDevices = null;
  }

  public int getTDevicesSize() {
    return (this.tDevices == null) ? 0 : this.tDevices.size();
  }

  public java.util.Iterator<TDeviceInfo> getTDevicesIterator() {
    return (this.tDevices == null) ? null : this.tDevices.iterator();
  }

  public void addToTDevices(TDeviceInfo elem) {
    if (this.tDevices == null) {
      this.tDevices = new ArrayList<TDeviceInfo>();
    }
    this.tDevices.add(elem);
  }

  public List<TDeviceInfo> getTDevices() {
    return this.tDevices;
  }

  public void setTDevices(List<TDeviceInfo> tDevices) {
    this.tDevices = tDevices;
  }

  public void unsetTDevices() {
    this.tDevices = null;
  }

  /** Returns true if field tDevices is set (has been assigned a value) and false otherwise */
  public boolean isSetTDevices() {
    return this.tDevices != null;
  }

  public void setTDevicesIsSet(boolean value) {
    if (!value) {
      this.tDevices = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case T_DEVICES:
      if (value == null) {
        unsetTDevices();
      } else {
        setTDevices((List<TDeviceInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case T_DEVICES:
      return getTDevices();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case T_DEVICES:
      return isSetTDevices();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TDevices)
      return this.equals((TDevices)that);
    return false;
  }

  public boolean equals(TDevices that) {
    if (that == null)
      return false;

    boolean this_present_tDevices = true && this.isSetTDevices();
    boolean that_present_tDevices = true && that.isSetTDevices();
    if (this_present_tDevices || that_present_tDevices) {
      if (!(this_present_tDevices && that_present_tDevices))
        return false;
      if (!this.tDevices.equals(that.tDevices))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_tDevices = true && (isSetTDevices());
    list.add(present_tDevices);
    if (present_tDevices)
      list.add(tDevices);

    return list.hashCode();
  }

  @Override
  public int compareTo(TDevices other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTDevices()).compareTo(other.isSetTDevices());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTDevices()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tDevices, other.tDevices);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TDevices(");
    boolean first = true;

    sb.append("tDevices:");
    if (this.tDevices == null) {
      sb.append("null");
    } else {
      sb.append(this.tDevices);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDevicesStandardSchemeFactory implements SchemeFactory {
    public TDevicesStandardScheme getScheme() {
      return new TDevicesStandardScheme();
    }
  }

  private static class TDevicesStandardScheme extends StandardScheme<TDevices> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDevices struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // T_DEVICES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.tDevices = new ArrayList<TDeviceInfo>(_list24.size);
                TDeviceInfo _elem25;
                for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                {
                  _elem25 = new TDeviceInfo();
                  _elem25.read(iprot);
                  struct.tDevices.add(_elem25);
                }
                iprot.readListEnd();
              }
              struct.setTDevicesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDevices struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tDevices != null) {
        oprot.writeFieldBegin(T_DEVICES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tDevices.size()));
          for (TDeviceInfo _iter27 : struct.tDevices)
          {
            _iter27.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDevicesTupleSchemeFactory implements SchemeFactory {
    public TDevicesTupleScheme getScheme() {
      return new TDevicesTupleScheme();
    }
  }

  private static class TDevicesTupleScheme extends TupleScheme<TDevices> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDevices struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTDevices()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTDevices()) {
        {
          oprot.writeI32(struct.tDevices.size());
          for (TDeviceInfo _iter28 : struct.tDevices)
          {
            _iter28.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDevices struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tDevices = new ArrayList<TDeviceInfo>(_list29.size);
          TDeviceInfo _elem30;
          for (int _i31 = 0; _i31 < _list29.size; ++_i31)
          {
            _elem30 = new TDeviceInfo();
            _elem30.read(iprot);
            struct.tDevices.add(_elem30);
          }
        }
        struct.setTDevicesIsSet(true);
      }
    }
  }

}

