/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.navercorp.pinpoint.thrift.dto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-2-10")
public class TFileSystems implements org.apache.thrift.TBase<TFileSystems, TFileSystems._Fields>, java.io.Serializable, Cloneable, Comparable<TFileSystems> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TFileSystems");

  private static final org.apache.thrift.protocol.TField T_FILE_SYSTEM_INFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("tFileSystemInfos", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TFileSystemsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TFileSystemsTupleSchemeFactory());
  }

  private List<TFileSystemInfo> tFileSystemInfos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    T_FILE_SYSTEM_INFOS((short)1, "tFileSystemInfos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // T_FILE_SYSTEM_INFOS
          return T_FILE_SYSTEM_INFOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.T_FILE_SYSTEM_INFOS, new org.apache.thrift.meta_data.FieldMetaData("tFileSystemInfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TFileSystemInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TFileSystems.class, metaDataMap);
  }

  public TFileSystems() {
  }

  public TFileSystems(
    List<TFileSystemInfo> tFileSystemInfos)
  {
    this();
    this.tFileSystemInfos = tFileSystemInfos;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TFileSystems(TFileSystems other) {
    if (other.isSetTFileSystemInfos()) {
      List<TFileSystemInfo> __this__tFileSystemInfos = new ArrayList<TFileSystemInfo>(other.tFileSystemInfos.size());
      for (TFileSystemInfo other_element : other.tFileSystemInfos) {
        __this__tFileSystemInfos.add(new TFileSystemInfo(other_element));
      }
      this.tFileSystemInfos = __this__tFileSystemInfos;
    }
  }

  public TFileSystems deepCopy() {
    return new TFileSystems(this);
  }

  @Override
  public void clear() {
    this.tFileSystemInfos = null;
  }

  public int getTFileSystemInfosSize() {
    return (this.tFileSystemInfos == null) ? 0 : this.tFileSystemInfos.size();
  }

  public java.util.Iterator<TFileSystemInfo> getTFileSystemInfosIterator() {
    return (this.tFileSystemInfos == null) ? null : this.tFileSystemInfos.iterator();
  }

  public void addToTFileSystemInfos(TFileSystemInfo elem) {
    if (this.tFileSystemInfos == null) {
      this.tFileSystemInfos = new ArrayList<TFileSystemInfo>();
    }
    this.tFileSystemInfos.add(elem);
  }

  public List<TFileSystemInfo> getTFileSystemInfos() {
    return this.tFileSystemInfos;
  }

  public void setTFileSystemInfos(List<TFileSystemInfo> tFileSystemInfos) {
    this.tFileSystemInfos = tFileSystemInfos;
  }

  public void unsetTFileSystemInfos() {
    this.tFileSystemInfos = null;
  }

  /** Returns true if field tFileSystemInfos is set (has been assigned a value) and false otherwise */
  public boolean isSetTFileSystemInfos() {
    return this.tFileSystemInfos != null;
  }

  public void setTFileSystemInfosIsSet(boolean value) {
    if (!value) {
      this.tFileSystemInfos = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case T_FILE_SYSTEM_INFOS:
      if (value == null) {
        unsetTFileSystemInfos();
      } else {
        setTFileSystemInfos((List<TFileSystemInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case T_FILE_SYSTEM_INFOS:
      return getTFileSystemInfos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case T_FILE_SYSTEM_INFOS:
      return isSetTFileSystemInfos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TFileSystems)
      return this.equals((TFileSystems)that);
    return false;
  }

  public boolean equals(TFileSystems that) {
    if (that == null)
      return false;

    boolean this_present_tFileSystemInfos = true && this.isSetTFileSystemInfos();
    boolean that_present_tFileSystemInfos = true && that.isSetTFileSystemInfos();
    if (this_present_tFileSystemInfos || that_present_tFileSystemInfos) {
      if (!(this_present_tFileSystemInfos && that_present_tFileSystemInfos))
        return false;
      if (!this.tFileSystemInfos.equals(that.tFileSystemInfos))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_tFileSystemInfos = true && (isSetTFileSystemInfos());
    list.add(present_tFileSystemInfos);
    if (present_tFileSystemInfos)
      list.add(tFileSystemInfos);

    return list.hashCode();
  }

  @Override
  public int compareTo(TFileSystems other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTFileSystemInfos()).compareTo(other.isSetTFileSystemInfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTFileSystemInfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tFileSystemInfos, other.tFileSystemInfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TFileSystems(");
    boolean first = true;

    sb.append("tFileSystemInfos:");
    if (this.tFileSystemInfos == null) {
      sb.append("null");
    } else {
      sb.append(this.tFileSystemInfos);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TFileSystemsStandardSchemeFactory implements SchemeFactory {
    public TFileSystemsStandardScheme getScheme() {
      return new TFileSystemsStandardScheme();
    }
  }

  private static class TFileSystemsStandardScheme extends StandardScheme<TFileSystems> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TFileSystems struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // T_FILE_SYSTEM_INFOS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.tFileSystemInfos = new ArrayList<TFileSystemInfo>(_list32.size);
                TFileSystemInfo _elem33;
                for (int _i34 = 0; _i34 < _list32.size; ++_i34)
                {
                  _elem33 = new TFileSystemInfo();
                  _elem33.read(iprot);
                  struct.tFileSystemInfos.add(_elem33);
                }
                iprot.readListEnd();
              }
              struct.setTFileSystemInfosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TFileSystems struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tFileSystemInfos != null) {
        oprot.writeFieldBegin(T_FILE_SYSTEM_INFOS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tFileSystemInfos.size()));
          for (TFileSystemInfo _iter35 : struct.tFileSystemInfos)
          {
            _iter35.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TFileSystemsTupleSchemeFactory implements SchemeFactory {
    public TFileSystemsTupleScheme getScheme() {
      return new TFileSystemsTupleScheme();
    }
  }

  private static class TFileSystemsTupleScheme extends TupleScheme<TFileSystems> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TFileSystems struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTFileSystemInfos()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTFileSystemInfos()) {
        {
          oprot.writeI32(struct.tFileSystemInfos.size());
          for (TFileSystemInfo _iter36 : struct.tFileSystemInfos)
          {
            _iter36.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TFileSystems struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list37 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tFileSystemInfos = new ArrayList<TFileSystemInfo>(_list37.size);
          TFileSystemInfo _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = new TFileSystemInfo();
            _elem38.read(iprot);
            struct.tFileSystemInfos.add(_elem38);
          }
        }
        struct.setTFileSystemInfosIsSet(true);
      }
    }
  }

}

