FROM common/vnfpluginbase:0.1

MAINTAINER "gordon" <qian.guodong5@zte.com.cn>

WORKDIR /

ADD smartsight-simulator.tar.gz .

EXPOSE 5000 29993 29994 29995 29996 39995

CMD python smartsight_simulator.py
